name: BP_CI                                       
on:
 workflow_dispatch:        
# push:                                            
#   branches: [ master ]
jobs:
  build:                                            
    runs-on: ubuntu-latest
    name: CI Build      

    steps:
    - name: Checkout  
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for Release
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test BPUnitTestProject/BPUnitTestProject.csproj --configuration Release --no-build --settings tests.runsettings --collect "Code coverage" -l:trx

    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact: ''
        name: MS Tests                  
        path: '**.trx'
        reporter: 'dotnet-trx'
        
    - name: Publish Coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: '**/TestResults/**/coverage.cobertura.xml'
        badge: true
        format: markdown
        indicators: true
        output: both

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.1
      with:
        reports: '**/TestResults/**/coverage.cobertura.xml'
        targetdir: coveragereport
        classfilters: -BPCalculator.Pages.BloodPressureModel;-BPCalculator.Pages.ErrorModel

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: Coverage report
        path: ${{github.workspace}}/coveragereport
        
  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'BPCalculator'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 8            
          # fail if CVSS score is High >=8          
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.0
        with:
          args: >
            -Dsonar.organization=mnandikkara
            -Dsonar.projectKey=mnandikkara_bpcalculator
            -Dsonar.cs.opencover.reportsPaths=coverage.cobertura.xml
            -Dsonar.python.coverage.reportPaths=coverage.cobertura.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
