name: BP_CD                                       
on:
 workflow_dispatch:        
# push:                                            
#   branches: [ master ]
jobs:
  
  Deploy_To_Staging:                                             
    environment:
      name: Staging
      url: https://mn-bpcalculator-staging.azurewebsites.net/                                 
    runs-on: windows-latest
    env:
      AZURE_WEBAPP_NAME: mn-bpcalculator               # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project
    steps:
    - uses: actions/checkout@v4

    # publish web app ready for deployment
    - name: Publish web app
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
    
    # Deploy to Azure app service to staging slot using publish profile for staging slot
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                            
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}     # Define secret variable in environment
        slot-name: staging
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

    # Run Selenium tests
    - name: Run Selenium tests
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp/SeleniumTest.dll /Settings:SeleniumTest.runsettings --logger:"trx;LogFileName=selenium.trx"

    # Upload results of selenium tests
    - uses: actions/upload-artifact@v4
      with:
        name: Selenium Tests Results
        path: TestResults/selenium.trx

    # Publish selenium test results
    - uses: dorny/test-reporter@v1
      with:
          artifact: ''
          name: Selenium Tests                  
          path: TestResults/selenium.trx
          reporter: 'dotnet-trx'
          
  Blue_Green:
    needs: [K6_Perf_Test, ZAP_Baseline_Scan]
    environment:
      name: 'Production'
      url: https://mn-bpcalculator.azurewebsites.net/
    permissions:
      id-token: write
    runs-on: windows-latest
    steps:
    # login to Azure account
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # blue/green
    - name: swap staging and production slots
      run: |
        az webapp deployment slot swap -n mn-bpcalculator -g csdca1bpcalc --slot staging --target-slot production

  K6_Perf_Test:
    needs: Deploy_To_Staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image for k6
      run: docker pull grafana/k6

    - name: Run k6 load test, capture report
      run: docker run -i grafana/k6 run - <K6Tests/perf1.js > k6report.txt

    - uses: actions/upload-artifact@v4
      with:
        name: k6report
        path: k6report.txt
        
  ZAP_Baseline_Scan:
    needs: Deploy_To_Staging
    runs-on: ubuntu-latest
    env:
      URI: https://mn-bpcalculator-staging.azurewebsites.net/
    steps:
    - name: Pull Docker image for ZAP
      run: docker pull zaproxy/zap-weekly

    - name: Run baseline scan
      run: docker run -v /report:/zap/wrk/:rw --user root -t zaproxy/zap-weekly zap-baseline.py -t ${{env.URI}} -I -r zapreport.html
  
    - uses: actions/upload-artifact@v4
      name: upload ZAP report
      with:
        name: ZAPreport
        path: /report/zapreport.html      
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
