# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - mn-bpcalculator

on:
 workflow_dispatch:
 # push:
 #   branches:

jobs:

  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB0229D352B54C5B850A8972DA31A976 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AEE264D34D549A3B0507F1E504FDCAC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E078ECBD9CC44AEEA54A8D470D223D2E }}

      # blue/green
      - name: swap staging and production slots
        run: |
          az account show --query id --output tsv
          
